app/user/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, SubmitField, TextAreaField
from wtforms.validators import ValidationError, DataRequired, Length
import sqlalchemy as sa
from app import db
from app.models import User

class EditProfileForm(FlaskForm):
    username = StringField('Username', validators=[DataRequired()])
    about_me = TextAreaField('About me', validators=[Length(min=0, max=140)])
    submit = SubmitField('Submit')

    def __init__(self, original_username, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.original_username = original_username

    def validate_username(self, username):
        if username.data != self.original_username:
            user = db.session.scalar(sa.select(User).where(
                User.username == self.username.data))
            if user is not None:
                raise ValidationError('Please use a different username.')            
            
            
class EmptyForm(FlaskForm):
    submit = SubmitField('Submit')


class MessageForm(FlaskForm):
    message = TextAreaField('Message', validators=[
        DataRequired(), Length(min=1, max=140)])
    submit = SubmitField('Submit')

app/user/__init__.py
from flask import Blueprint

bp = Blueprint('user', __name__)

from app.user import routes

app/user/routes.py
from datetime import datetime, timezone
from flask import render_template, flash, redirect, url_for, request, current_app
from flask_login import current_user, login_required
import sqlalchemy as sa
from app import db
from app.user.forms import EditProfileForm, EmptyForm, MessageForm
from app.models import User, Project, Message, Notification
from app.user import bp



@bp.route('/<username>')
@login_required
def user(username):    
    user = db.first_or_404(sa.select(User).where(User.username == username))
    page = request.args.get('page', 1, type=int)
    query = user.projects.select().order_by(Project.timestamp.desc())
    projects = db.paginate(query, page=page,
                        per_page=current_app.config['PROJECTS_PER_PAGE'],
                        error_out=False)
    next_url = url_for('user.user', username=user.username, page=projects.next_num) \
        if projects.has_next else None
    prev_url = url_for('user.user', username=user.username, page=projects.prev_num) \
        if projects.has_prev else None
    form = EmptyForm()
    return render_template('user/user.html', user=user, projects=projects.items,
                           next_url=next_url, prev_url=prev_url, form=form)


@bp.route('/<username>/popup')
@login_required
def user_popup(username):        
    user = db.first_or_404(sa.select(User).where(User.username == username))         
    form = EmptyForm()
    return render_template('user/user_popup.html', user=user, form=form)


@bp.route('user/edit-profile', methods=['GET', 'POST'])
@login_required
def edit_profile():
    form = EditProfileForm(current_user.username)
    if form.validate_on_submit():
        current_user.username = form.username.data
        current_user.about_me = form.about_me.data
        db.session.commit()
        flash('Your changes have been saved.')
        return redirect(url_for('user.edit_profile'))
    elif request.method == 'GET':
        form.username.data = current_user.username
        form.about_me.data = current_user.about_me
    return render_template('user/edit_profile.html', title='Edit Profile',
                           form=form)


@bp.route('/follow/<username>', methods=['POST'])
@login_required
def follow(username):
    form = EmptyForm()
    if form.validate_on_submit():
        user = db.session.scalar(
            sa.select(User).where(User.username == username))
        if user is None:
            flash(f'User {username} not found.')
            return redirect(url_for('main.index'))
        if user == current_user:
            flash('You cannot follow yourself!')
            return redirect(url_for('user.user', username=username))
        current_user.follow(user)
        db.session.commit()
        flash(f'You are following {username}!')
        return redirect(url_for('user.user', username=username))
    else:
        return redirect(url_for('main.index'))


@bp.route('/unfollow/<username>', methods=['POST'])
@login_required
def unfollow(username):
    form = EmptyForm()
    if form.validate_on_submit():
        user = db.session.scalar(
            sa.select(User).where(User.username == username))
        if user is None:
            flash(f'User {username} not found.')
            return redirect(url_for('main.index'))
        if user == current_user:
            flash('You cannot unfollow yourself!')
            return redirect(url_for('user.user', username=username))
        current_user.unfollow(user)
        db.session.commit()
        flash(f'You no longer follow {username}.')
        return redirect(url_for('user.user', username=username))
    else:
        return redirect(url_for('main.index'))
    

@bp.route('/send_message/<recipient>', methods=['GET', 'POST'])
@login_required
def send_message(recipient):
    user = db.first_or_404(sa.select(User).where(User.username == recipient))
    form = MessageForm()
    if form.validate_on_submit():
        msg = Message(author=current_user, recipient=user,
                      body=form.message.data)
        db.session.add(msg)
        user.add_notification('unread_message_count',
                              user.unread_message_count())
        db.session.commit()
        flash('Your message has been sent.')
        return redirect(url_for('user.user', username=recipient))
    return render_template('user/send_message.html', title='Send Message',
                           form=form, recipient=recipient)

@bp.route('/messages')
@login_required
def messages():
    current_user.last_message_read_time = datetime.now(timezone.utc)
    current_user.add_notification('unread_message_count', 0)
    db.session.commit()
    page = request.args.get('page', 1, type=int)
    query = current_user.messages_received.select().order_by(
        Message.timestamp.desc())
    messages = db.paginate(query, page=page,
                           per_page=current_app.config['PROJECTS_PER_PAGE'],
                           error_out=False)
    next_url = url_for('main.messages', page=messages.next_num) \
        if messages.has_next else None
    prev_url = url_for('main.messages', page=messages.prev_num) \
        if messages.has_prev else None
    return render_template('user/messages.html', messages=messages.items,
                           next_url=next_url, prev_url=prev_url)


@bp.route('/notifications')
@login_required
def notifications():
    since = request.args.get('since', 0.0, type=float)
    query = current_user.notifications.select().where(
        Notification.timestamp > since).order_by(Notification.timestamp.asc())
    notifications = db.session.scalars(query)
    return [{
        'name': n.name,
        'data': n.get_data(),
        'timestamp': n.timestamp
    } for n in notifications]


@bp.route('/export_projects')
@login_required
def export_projects():
    if current_user.get_task_in_progress('export_projects'):
        flash(_('An export task is currently in progress'))
    else:
        current_user.launch_task('export_projects', 'Exporting projects...')
        db.session.commit()
    return redirect(url_for('user.user', username=current_user.username))

app/templates/user/_message.html
<table class="table table-hover">
    <tr>
        <td width="70px">
            <a href="{{ url_for('user.user', username=message.author.username) }}">
                <img src="{{ message.author.avatar(70) }}" />
            </a>
        </td>
        <td>
            <a class="user_popup" href="{{ url_for('user.user', username=message.author.username) }}">
                {{ message.author.username }}
            </a>
            said {{ moment(message.timestamp).fromNow() }}:
            <br>
            {{ message.body }}
        </td>
    </tr>
</table>

app/templates/user/edit_profile.html
{% extends "base.html" %}
{% import "bootstrap_wtf.html" as wtf %}

{% block content %}
    <h1>Edit Profile</h1>
    {{ wtf.quick_form(form) }}
{% endblock %}

app/templates/user/messages.html
{% extends "base.html" %}

{% block content %}
    <h1>{{ 'Messages' }}</h1>
    {% for message in messages %}
        {% include 'user/_message.html' %}
    {% endfor %}
    <nav aria-label="Post navigation">
        <ul class="pagination">
            <li class="page-item{% if not prev_url %} disabled{% endif %}">
                <a class="page-link" href="#">
                    <span aria-hidden="true">&larr;</span> {{ 'Newer messages' }}
                </a>
            </li>
            <li class="page-item{% if not next_url %} disabled{% endif %}">
                <a class="page-link" href="#">
                    {{ 'Older messages' }} <span aria-hidden="true">&rarr;</span>
                </a>
            </li>
        </ul>
    </nav>
{% endblock %}

app/templates/user/send_message.html
{% extends "base.html" %}
{% import "bootstrap_wtf.html" as wtf %}

{% block content %}
    <h1>Send Message to {{ recipient }}</h1>
    {{ wtf.quick_form(form) }}
{% endblock %}

app/templates/user/user.html
{% extends "base.html" %}

{% block content %}
    <table class="table table-hover">
        <tr>
            <td width="256px"><img src="{{ user.avatar(256) }}"></td>
            <td>
                <h1>User: {{ user.username }}</h1>
                {% if user.about_me %}<p>{{ user.about_me }}</p>{% endif %}
                {% if user.last_seen %}
                <p>Last seen on: {{ moment(user.last_seen).format('LLL') }}</p>
                {% endif %}
                <p>{{ user.followers_count() }} followers, {{ user.following_count() }} following.</p>
                {% if user == current_user %}
                <p><a href="{{ url_for('user.edit_profile') }}">Edit your profile</a></p>
                {% if not current_user.get_task_in_progress('export_projects') %}
                <p><a href="{{ url_for('user.export_projects') }}">{{ 'Export your projects' }}</a></p>
                {% endif %}
                {% elif not current_user.is_following(user) %}
                <p>
                    <form action="{{ url_for('user.follow', username=user.username) }}" method="post">
                        {{ form.hidden_tag() }}
                        {{ form.submit(value='Follow', class_='btn btn-primary') }}
                    </form>
                </p>
                {% else %}
                <p>
                    <form action="{{ url_for('user.unfollow', username=user.username) }}" method="post">
                        {{ form.hidden_tag() }}
                        {{ form.submit(value='Unfollow', class_='btn btn-primary') }}
                    </form>
                </p>
                {% endif %}
                {% if user != current_user %}
                <p><a href="{{ url_for('user.send_message', recipient=user.username) }}">{{ 'Send private message' }}</a></p>
                {% endif %}
            </td>
        </tr>
    </table>
    {% if current_user.is_following(user) or current_user == user %}
        {% for project in projects %}
            {% include '_project.html' %}
        {% endfor %}
    {% endif %}
    <nav aria-label="Project navigation">
        <ul class="pagination">
            <li class="page-item{% if not prev_url %} disabled{% endif %}">
                <a class="page-link" href="{{ prev_url }}">
                    <span aria-hidden="true">&larr;</span> Newer projects
                </a>
            </li>
            <li class="page-item{% if not next_url %} disabled{% endif %}">
                <a class="page-link" href="{{ next_url }}">
                    Older projects <span aria-hidden="true">&rarr;</span>
                </a>
            </li>
        </ul>
    </nav>
{% endblock %}

app/templates/user/user_popup.html
<div>
    <img src="{{ user.avatar(64) }}" style="margin: 5px; float: left">
    <p><a href="{{ url_for('user.user', username=user.username) }}">{{ user.username }}</a></p>
    {% if user.about_me %}<p>{{ user.about_me }}</p>{% endif %}
    <div class="clearfix"></div>
    {% if user.last_seen %}    
    <p>Last seen on: {{ moment(user.last_seen).format('lll') }}</p>
    {% endif %}    
    <p>{{user.followers_count() }} followers, {{ user.following_count() }} following</p>
    {% if user != current_user %}
      {% if not current_user.is_following(user) %}
      <p>
        <form action="{{ url_for('user.follow', username=user.username) }}" method="post">
          {{ form.hidden_tag() }}
          {{ form.submit(value='Follow', class_='btn btn-outline-primary btn-sm') }}
        </form>
      </p>
      {% else %}
      <p>
        <form action="{{ url_for('user.unfollow', username=user.username) }}" method="post">
          {{ form.hidden_tag() }}
          {{ form.submit(value='Unfollow', class_='btn btn-outline-primary btn-sm') }}
        </form>
      </p>
      {% endif %}
    {% endif %}
  </div>